version: "3.9"

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_local
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env

  postgres:
    image: postgres:latest
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file: .env
